// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwOTQASMNfAQbZkxfe4LsJKmCWtMvmMRs',
    appId: '1:1039570233916:web:febf6ffc74bc647ccb3139',
    messagingSenderId: '1039570233916',
    projectId: 'fluttertask-9d151',
    authDomain: 'fluttertask-9d151.firebaseapp.com',
    storageBucket: 'fluttertask-9d151.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn4kZ5DuimeO_FMBqLmI78vcWGBZzGM20',
    appId: '1:1039570233916:android:6c3b452ac9fe1b1ecb3139',
    messagingSenderId: '1039570233916',
    projectId: 'fluttertask-9d151',
    storageBucket: 'fluttertask-9d151.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFj6vhI5PNGgwge2brZ8ScGmUXDqVtE5s',
    appId: '1:1039570233916:ios:b398037e837c6bf5cb3139',
    messagingSenderId: '1039570233916',
    projectId: 'fluttertask-9d151',
    storageBucket: 'fluttertask-9d151.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFj6vhI5PNGgwge2brZ8ScGmUXDqVtE5s',
    appId: '1:1039570233916:ios:b398037e837c6bf5cb3139',
    messagingSenderId: '1039570233916',
    projectId: 'fluttertask-9d151',
    storageBucket: 'fluttertask-9d151.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwOTQASMNfAQbZkxfe4LsJKmCWtMvmMRs',
    appId: '1:1039570233916:web:7de2579e3ddb3a64cb3139',
    messagingSenderId: '1039570233916',
    projectId: 'fluttertask-9d151',
    authDomain: 'fluttertask-9d151.firebaseapp.com',
    storageBucket: 'fluttertask-9d151.firebasestorage.app',
  );
}
